general:
  project_name: handposture
  model_path: null
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: true
  global_seed: 42
  gpu_memory_limit: 24
  deterministic_ops: true
operation_mode: training
dataset:
  name: ST_handposture_dataset
  class_names:
  - None
  - Like
  - Dislike
  - FlatHand
  - Fist
  - Love
  - BreakTime
  - CrossHands
  training_path: ../datasets/ST_VL53L5CX_handposture_dataset
  validation_path: null
  validation_split: null
  test_path: null
preprocessing:
  Max_distance: 400
  Min_distance: 100
  Background_distance: 120
data_augmentation:
  random_flip:
    mode: horizontal
training:
  model:
    name: CNN2D_ST_HandPosture
    version: v1
    input_shape: (8, 8, 2)
  frozen_layers: null
  dropout: 0.2
  batch_size: 32
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:
    ReduceLROnPlateau:
      monitor: val_loss
      factor: 0.1
      patience: 20
      min_lr: 0.0001
    EarlyStopping:
      monitor: val_accuracy
      restore_best_weights: true
      patience: 40
tools:
  stedgeai:
    version: 9.1.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.15.0/STM32CubeIDE/stm32cubeide.exe
benchmarking:
  board: NUCLEO-F401RE
deployment:
  c_project_path: ../../stm32ai_application_code/hand_posture/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32F4
    board: NUCLEO-F401RE
mlflow:
  uri: ./experiments_outputs/mlruns
hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
