general:
  project_name: handposture

dataset:
  name: ST_handposture_dataset
  class_names: [None, Like, Dislike, FlatHand, Fist, Love, BreakTime, CrossHands]
  test_path: ../training/datasets/ST_VL53L5CX_handposture_test

pre_processing:
  Max_distance: 350
  Min_distance: 150
  Background_distance: 120


model:
  model_type: {name : CNN2D_ST_HandPosture, version : v1}
  input_shape: [8, 8, 2]
  model_path: ../../models/CNN2D_ST_HandPosture/ST_pretrainedmodel_custom_dataset/ST_VL53L5CX_handposture_dataset/CNN2D_ST_HandPosture_8classes/CNN2D_ST_HandPosture_8classes.h5

stm32ai:
  optimization: balanced
  footprints_on_target: STM32L4R9I-DISCO
  path_to_stm32ai: C:/Work/AI/Cube.AI/7.3.0/windows/stm32ai.exe

mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}