general:
  project_name: CIFAR100
  model_path: null
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: true
  global_seed: 127
  gpu_memory_limit: 20
operation_mode: chain_tbqeb
dataset:
  name: cifar100
  class_names: [beaver,dolphin,otter,seal,whale,aquarium_fish,flatfish,ray,shark,trout,orchids,poppies,roses,sunflowers,tulips,bottles,bowls,cans,cups,plates,apples,mushrooms,oranges,pears,sweet_peppers,clock,computer_keyboard,lamp,telephone,television,bed,chair,couch,table,wardrobe,bee,beetle,butterfly,caterpillar,cockroach,bear,leopard,lion,tiger,wolf,bridge,castle,house,road,skyscraper,cloud,forest,mountain,plain,sea,camel,cattle,chimpanzee,elephant,kangaroo,fox,porcupine,possum,raccoon,skunk,crab,lobster,snail,spider,worm,baby,boy,girl,man,woman,crocodile,dinosaur,lizard,snake,turtle,hamster,mouse,rabbit,shrew,squirrel,maple,oak,palm,pine,willow,bicycle,bus,motorcycle,pickup_truck,train,lawn-mower,rocket,streetcar,tank,tractor]
  training_path: ../datasets/cifar-100/cifar-100-python
  validation_path: null
  validation_split: 0.2
  test_path: null
  quantization_path: null
  quantization_split: null
  check_image_files: false
  seed: 127
preprocessing:
  rescaling:
    scale: 1/255.0
    offset: 0
  resizing:
    interpolation: nearest
    aspect_ratio: fit
  color_mode: rgb
data_augmentation:
  random_posterize:
    bits: (4, 8)
    change_rate: 0.145
  random_hue:
    delta: 0.04
    change_rate: 1.0
  random_contrast:
    factor: 0.275
    change_rate: 1.0
  random_brightness:
    factor: 0.175
    change_rate: 1.0
  random_rectangle_erasing:
    nrec: (0, 10)
    area: (0.0, 0.1)
    wh_ratio: (0.25, 4.0)
    fill_method: mosaic
    mode: batch
    change_rate: 0.125
  random_flip:
    mode: horizontal
    change_rate: 1.0
  random_translation:
    width_factor: 0.175
    height_factor: 0.175
    fill_mode: reflect
    interpolation: nearest
    change_rate: 1.0
  random_rotation:
    factor: 0.1
    fill_mode: reflect
    interpolation: nearest
    change_rate: 1.0
  random_zoom:
    width_factor: 0.175
    height_factor: 0.175
    fill_mode: reflect
    interpolation: nearest
    change_rate: 1.0
  random_shear:
    factor: 0.1
    fill_mode: wrap
    interpolation: nearest
    change_rate: 1.0
training:
  model:
    name: resnet
    version: v1
    depth: 32
    input_shape: (32, 32, 3)
  resume_training_from: null
  dropout: 0.15
  batch_size: 64
  epochs: 3000
  optimizer:
    Adam:
      learning_rate: 0.001
  callbacks:
    ReduceLROnPlateau:
      monitor: val_accuracy
      mode: max
      factor: 0.75
      patience: 100
      min_lr: 2.5e-06
    EarlyStopping:
      monitor: val_accuracy
      mode: max
      restore_best_weights: true
      patience: 500
quantization:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
prediction: null
tools:
  stm32ai:
    version: 8.1.0
    optimization: balanced
    on_cloud: true
    path_to_stm32ai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stm32ai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.10.1/STM32CubeIDE/stm32cubeide.exe
benchmarking:
  board: STM32H747I-DISCO
deployment:
  c_project_path: ../../stm32ai_application_code/image_classification/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32H7
    board: STM32H747I-DISCO
    input: CAMERA_INTERFACE_DCMI
    output: DISPLAY_INTERFACE_USB
mlflow:
  uri: ./experiments_outputs/mlruns
