general:
  project_name: tf_flowers
  logs_dir: logs
  saved_models_dir: saved_models
train_parameters:
  batch_size: 64
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau
dataset:
  name: flowers
  class_names:
  - daisy
  - dandelion
  - roses
  - sunflowers
  - tulips
  training_path: datasets/flower_photos
  validation_path: null
  test_path: null
pre_processing:
  rescaling:
    scale: 127.5
    offset: -1
  resizing: nearest
  aspect_ratio: false
  color_mode: rgb
data_augmentation:
  RandomFlip: horizontal_and_vertical
  RandomTranslation:
  - 0.1
  - 0.1
  RandomRotation: 0.2
  RandomZoom: 0.2
  RandomContrast: 0.2
  RandomBrightness: 0.4
  RandomShear: false
model:
  model_type:
    name: mobilenet
    version: v1
    alpha: 0.25
  input_shape:
  - 224
  - 224
  - 3
  transfer_learning: true
  dropout: 0.25
quantization:
  quantize: true
  evaluate: true
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
stm32ai:
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: C:/stmicroelectronics/cubeai_7_3_0/windows/stm32ai.exe
mlflow:
  uri: ./mlruns
