general:
  project_name: Person_Demo

dataset:
  name: COCO_Person
  class_names: [person]
  training_path:
  validation_path:
  test_path:

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: bilinear
  aspect_ratio: False
  color_mode: rgb

post_processing:
  type: SSD
  confidence_thresh: 0.5
  NMS_thresh: 0.5

model:
  model_type: {name : mobilenet, version : v1, alpha : 0.25}
  input_shape: [192, 192, 3]
  model_path: ../../models/ssd_mobilenetv1/ST_pretrainedmodel_public_dataset/COCO/ssd_mobilenet_v1_0.25_192/ssd_mobilenet_v1_025_192_int8.tflite

quantization:
  quantize: False
  evaluate: False
  quantization_dataset:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  c_project_path: ../../getting_started
  serie: STM32H7
  IDE: GCC
  verbosity: 1
  version: 8.0.1
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: C:/ST/STM32CubeAI/en.x-cube-ai-windows_v7.3.0/windows/stm32ai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.10.1/STM32CubeIDE/stm32cubeide.exe

mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
