general:
  project_name: handposture
  model_path:
  logs_dir: logs
  saved_models_dir: saved_models
  display_figures: True
  global_seed: 42
  gpu_memory_limit: 24
  deterministic_ops: True

operation_mode: training
#choices=['training' , 'evaluation', 'deployment', 'benchmarking']

dataset:
  name: ST_handposture_dataset
  class_names: [None, Like, Dislike, FlatHand, Fist, Love, BreakTime, CrossHands] # Mandatory and aligned with utils/handposture_dictionnary.py
  training_path: ../datasets/ST_VL53L8CX_handposture_dataset  # Mandatory
  validation_path:    # Optional
  validation_split:   # Optional, default value is 0.2
  test_path:          # Optional

preprocessing: # Mandatory
  Max_distance: 400 # Mandatory
  Min_distance: 100 # Mandatory
  Background_distance:  120 # Mandatory

data_augmentation:    # Optional section
  random_flip:
    mode: horizontal # horizontal, vertical or horizontal_and_vertical

training:
  model:    # Use it if you want to use a model from the zoo, mutually exclusive with 'general.model_path'
    name: CNN2D_ST_HandPosture # custom
    version: v1
    input_shape: (8, 8, 2)
  frozen_layers: #(0:-1)            # Optional, use if you want to freeze some layers (by default all layers are trainable)
  dropout: 0.2                     # Optional, use it if you want a dropout layer to be included in the model
  batch_size: 32
  epochs: 1000
  optimizer:
    Adam:
      learning_rate: 0.01
  callbacks:          # Optional section
    ReduceLROnPlateau:
      monitor: val_loss
      factor: 0.1
      patience: 20
      min_lr: 1.0e-04
    EarlyStopping:
      monitor: val_accuracy
      restore_best_weights: true
      patience: 40
#  trained_model_path: trained.h5   # Optional, use it if you want to save the best model at the end of the training to a path of your choice

tools:
  stedgeai:
    version: 9.1.0
    optimization: balanced
    on_cloud: True
    path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.15.0/STM32CubeIDE/stm32cubeide.exe

benchmarking:
  board: NUCLEO-F401RE

deployment:
  c_project_path: ../../stm32ai_application_code/hand_posture/
  IDE: GCC
  verbosity: 1
  hardware_setup:
    serie: STM32F4
    board: NUCLEO-F401RE

mlflow:
  uri: ./experiments_outputs/mlruns

hydra:
  run:
    dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
