general:
   model_path: path/to/stm32-hotspot/ultralytics/yolov8n_256_quant_pt_uf_pose_coco-st.tflite
   model_type: yolo_mpe

operation_mode: deployment

dataset:
   keypoints: 17
   test_path: ../datasets/coco_val_single_pose

preprocessing:
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

tools:
   stedgeai:
      version: 9.1.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_1.15.0/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path: ../../X-LINUX-AI_application_code/pose_estimation/
   label_file_path: ../../X-LINUX-AI_application_code/pose_estimation/Resources/keypoints_yolov8.txt
   board_deploy_path: /usr/local/pose-estimation
   verbosity: 1
   hardware_setup:
      serie: STM32MP2
      board: STM32MP257F-EV1
      ip_address: X.X.X.X

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}