general:
   model_path: ../pretrained_models/movenet/Public_pretrainedmodel_custom_dataset/custom_dataset_person_17kpts/movenet_lightning_heatmaps_192/movenet_lightning_heatmaps_192_int8.tflite
   model_type: heatmaps_spe  # spe, yolo_mpe

operation_mode: prediction

dataset:
   keypoints: 17  # 13

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

postprocessing:
   kpts_conf_thresh: 0.15

prediction:
   test_files_path: ../datasets/coco_test_single_pose

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
