general:
   model_path: ../pretrained_models/deeplab_v3/ST_pretrainedmodel_public_dataset/coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_512_fft/deeplab_v3_mobilenetv2_05_16_512_fft.h5
operation_mode: chain_qd

dataset:
  name: pascal_voc
  class_names: [ "background", "aeroplane", "bicycle", "bird", "boat", "bottle", "bus",
                 "car", "cat", "chair", "cow", "dining table", "dog", "horse", "motorbike",
                 "person", "potted plant", "sheep", "sofa", "train", "tv/monitor" ]
  quantization_path: ../datasets/VOC2012_train_val/JPEGImages
  quantization_masks_path: ../datasets/VOC2012_train_val/SegmentationClassAug
  quantization_files_path: ../datasets/VOC2012_train_val/ImageSets/Segmentation/train.txt

preprocessing:
  rescaling:
    scale: 1/127.5
    offset: -1
  resizing:
    aspect_ratio: fit
    interpolation: bilinear
  color_mode: rgb

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float

tools:
   stedgeai:
      version: 9.1.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_1.15.0/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path:  ../../X-LINUX-AI_application_code/semantic_segmentation/
   label_file_path: ../../X-LINUX-AI_application_code/semantic_segmentation/Resources/labelmap.txt
   board_deploy_path: /usr/local/semantic-segmentation
   verbosity: 1
   hardware_setup:
      serie: STM32MP2
      board: STM32MP257F-EV1
      ip_address: X.X.X.X

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}