general:
   model_path:  ../path/to/X-LINUX-AI/deeplabv3_257_int8_per_tensor.tflite

operation_mode: deployment

dataset:
   name: pascal_voc
   class_names: [ "background", "aeroplane", "bicycle", "bird", "boat", "bottle", "bus",
                  "car", "cat", "chair", "cow", "dining table", "dog", "horse", "motorbike",
                  "person", "potted plant", "sheep", "sofa", "train", "tv/monitor" ]

preprocessing:
   resizing:
      interpolation: nearest
      aspect_ratio: fit
   color_mode: rgb

tools:
   stedgeai:
      version: 9.1.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stedgeai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_1.15.0/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path:  ../../X-LINUX-AI_application_code/semantic_segmentation/
   label_file_path: ../../X-LINUX-AI_application_code/semantic_segmentation/Resources/labelmap.txt
   board_deploy_path: /usr/local/semantic-segmentation
   verbosity: 1
   hardware_setup:
      serie: STM32MP2
      board: STM32MP257F-EV1
      ip_address: X.X.X.X

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}