general:
   model_path: ../pretrained_models/deeplab_v3/ST_pretrainedmodel_public_dataset/coco_2017_pascal_voc_2012/deeplab_v3_mobilenetv2_05_16_512_fft/deeplab_v3_mobilenetv2_05_16_512_fft.h5
   
operation_mode: prediction

dataset:
   name: pascal_voc
   class_names: [ "background", "aeroplane", "bicycle", "bird", "boat", "bottle", "bus",
                  "car", "cat", "chair", "cow", "dining table", "dog", "horse", "motorbike",
                  "person", "potted plant", "sheep", "sofa", "train", "tv/monitor" ]

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

prediction:
   test_files_path: ../datasets/VOC2012_test_nano/

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}
