general:
   model_path: ../pretrained_models/squeezenetv1.1/ST_pretrainedmodel_public_dataset/plant-village/squeezenetv1.1_128_tfs/squeezenetv1.1_128_tfs.h5

operation_mode: chain_qd

dataset:
  class_names:
  - Apple___Apple_scab
  - Apple___Black_rot
  - Apple___Cedar_apple_rust
  - Apple___healthy
  - Background_without_leaves
  - Blueberry___healthy
  - Cherry___healthy
  - Cherry___Powdery_mildew
  - Corn___Cercospora_leaf_spot Gray_leaf_spot
  - Corn___Common_rust
  - Corn___healthy
  - Corn___Northern_Leaf_Blight
  - Grape___Black_rot
  - Grape___Esca_(Black_Measles)
  - Grape___healthy
  - Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
  - Orange___Haunglongbing_(Citrus_greening)
  - Peach___Bacterial_spot
  - Peach___healthy
  - Pepper,_bell___Bacterial_spot
  - Pepper,_bell___healthy
  - Potato___Early_blight
  - Potato___healthy
  - Potato___Late_blight
  - Raspberry___healthy
  - Soybean___healthy
  - Squash___Powdery_mildew
  - Strawberry___healthy
  - Strawberry___Leaf_scorch
  - Tomato___Bacterial_spot
  - Tomato___Early_blight
  - Tomato___healthy
  - Tomato___Late_blight
  - Tomato___Leaf_Mold
  - Tomato___Septoria_leaf_spot
  - Tomato___Spider_mites Two-spotted_spider_mite
  - Tomato___Target_Spot
  - Tomato___Tomato_mosaic_virus
  - Tomato___Tomato_Yellow_Leaf_Curl_Virus
  quantization_path: ../datasets/Plant_leave_diseases_dataset_without_augmentation
  quantization_split: 0.5

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

quantization:
   quantizer: TFlite_converter
   quantization_type: PTQ
   quantization_input_type: uint8
   quantization_output_type: float

tools:
   stm32ai:
      version: 8.1.0
      optimization: balanced
      on_cloud: True
      path_to_stm32ai: C:/Users/<XXXXX>/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/<*.*.*>/Utilities/windows/stm32ai.exe
   path_to_cubeIDE: C:/ST/STM32CubeIDE_1.10.1/STM32CubeIDE/stm32cubeide.exe

deployment:
   c_project_path: ../../stm32ai_application_code/image_classification/
   IDE: GCC
   verbosity: 1
   hardware_setup:
      serie: STM32H7
      board: STM32H747I-DISCO
      input: CAMERA_INTERFACE_DCMI
      output: DISPLAY_INTERFACE_USB

mlflow:
   uri: ./experiments_outputs/mlruns

hydra:
   run:
      dir: ./experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}